---
# https://github.com/marketplace/actions/s3-sync
#
name: Upload Website to S3
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: pre-commit tests
        uses: pre-commit/action@v3.0.1

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: >
            --acl public-read --follow-symlinks --delete
            --exclude '.git/*' --exclude '.github/*'
            --exclude '.pre-commit-config.yaml'
            --exclude 'README.md'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'makeitwork.cloud/'

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: >
            --acl public-read --follow-symlinks --delete
            --exclude '.git/*' --exclude '.github/*'
            --exclude '.pre-commit-config.yaml'
            --exclude 'README.md'
        env:
          AWS_S3_BUCKET: ${{ secrets.ONION_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ONION_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ONION_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.ONION_AWS_REGION }}
          SOURCE_DIR: 'onion.makeitwork.cloud/'

      - name: Purge Cloudflare Cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
